[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://agrieasy-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
